
;----------------------------------------------------------------------------------------------------------------------------------------------------------------
;请先认真阅读《额外功能说明》中的##使用须知
;----------------------------------------------------------------------------------------------------------------------------------------------------------------

;【注意】引用的图像、武器、弹头自行补充

; A.手枪
; SOMEIMAGEA1 - 抛射体图像，自行设定，后同
[SOMEPROJECTILEA1]
AA=no
AG=yes
Inaccurate=yes
FlakScatter=yes
BallisticScatter.Min=0
BallisticScatter.Max=0.5
SubjectToCliffs=yes
SubjectToElevation=yes
SubjectToWalls=yes
SubjectToBuildings=yes
SubjectToGround=yes
Image=SOMEIMAGEA1
Trajectory=Straight
Trajectory.DetonationDistance=0
Trajectory.TargetSnapDistance=0
Trajectory.Speed=400.0

; B.霰弹枪
; SOMEWEAPONB2 - 用于发射 SOMEPROJECTILEB2 的武器，后同
; 武器发射后，抛体就会消失
[SOMEPROJECTILEB1]
AA=no
AG=yes
SubjectToCliffs=yes
SubjectToElevation=no
SubjectToWalls=yes
SubjectToBuildings=yes
SubjectToGround=yes
Image=SOMEIMAGEB1
Trajectory=Missile
Trajectory.Missile.LaunchSpeed=0
Trajectory.Missile.Acceleration=0
Trajectory.Missile.TurningSpeed=0
Trajectory.Missile.LockDirection=yes
DisperseSuicide=yes
DisperseWeapons=SOMEWEAPONB2
DisperseBursts=5
DisperseCounts=1
DisperseCycle=1
Trajectory.Speed=0

; 接触到第一个单位时引爆，并引爆额外弹头 SOMEWARHEADB2 ，非同格但在半径内的车辆、建筑不会引爆它，
; 关闭镜像坐标可以保证抛体不会在非单位本体发射时再次镜像发射角度而导致两两重叠
[SOMEPROJECTILEB2]
AA=no
AG=yes
SubjectToCliffs=yes
SubjectToElevation=no
SubjectToWalls=yes
SubjectToBuildings=yes
Image=SOMEIMAGEB2
Trajectory=Straight
ApplyRangeModifiers=yes
Trajectory.RotateCoord=15
Trajectory.MirrorCoord=no
Trajectory.DetonationDistance=-0.5
Trajectory.TargetSnapDistance=0
Trajectory.Straight.PassThrough=yes
PeacefulVanish=no
ProximityImpact=1
ProximityWarhead=SOMEWARHEADB2
ProximityDamage=50
ProximityRadius=0.4
ProximityDirect=yes
PassThroughVehicles=no
PassThroughBuilding=no
DamageEdgeAttenuation=0.6
Trajectory.Speed=300.0

; C.光翼展开
; 发射坐标、镜像坐标和坐标旋转轴共同决定了导弹发射时的初始移动方向
[SOMEPROJECTILEC1]
AA=yes
AG=yes
SubjectToCliffs=no
SubjectToElevation=no
SubjectToWalls=no
Image=SOMEIMAGEC1
Trajectory=Missile
Trajectory.Missile.PreAimCoord=0,200,250
Trajectory.Missile.ReduceCoord=no
Trajectory.RotateCoord=120
Trajectory.AxisOfRotation=-1,0,0
Trajectory.Missile.LaunchSpeed=50
Trajectory.Missile.Acceleration=10
Trajectory.Missile.TurningSpeed=20
RetargetRadius=4
Trajectory.Speed=250.0

; D.喷火器
; 抛体经过时，会使所有半径内的不重复的步兵受到伤害，弹头比例由 SOMEWARHEADD1 决定，
; 会伤害友军，在接触到车辆、建筑时会直接引爆，否则沿地形飞行固定距离后才会引爆
[SOMEPROJECTILED1]
AA=no
AG=yes
Inaccurate=yes
FlakScatter=yes
BallisticScatter.Min=0.8
BallisticScatter.Max=1.2
SubjectToCliffs=yes
SubjectToElevation=no
SubjectToWalls=yes
SubjectToBuildings=yes
Image=SOMEIMAGED1
Trajectory=Straight
ApplyRangeModifiers=yes
Trajectory.DetonationDistance=4.7
Trajectory.TargetSnapDistance=0
Trajectory.Straight.PassThrough=yes
ProximityImpact=-1
ProximityWarhead=SOMEWARHEADD1
ProximityDamage=40
ProximityRadius=0.8
ProximityDirect=yes
ProximityAllies=yes
PassThroughVehicles=no
PassThroughBuilding=no
Trajectory.Straight.ConfineAtHeight=75
Trajectory.Speed=60.0

; E.重机枪
; 抛体经过时，会使所有半径内的不重复的步兵、车辆受到伤害，弹头比例由 SOMEWARHEADE1 决定，
; 伤害会随距离衰减，最多伤害3个目标，在接触到建筑时会直接引爆，否则在飞行到目标身后固定距离才会引爆
[SOMEPROJECTILEE1]
AA=no
AG=yes
Inaccurate=yes
FlakScatter=yes
BallisticScatter.Min=0.25
BallisticScatter.Max=0.75
SubjectToCliffs=yes
SubjectToElevation=no
SubjectToWalls=yes
SubjectToBuildings=yes
SubjectToGround=yes
Image=SOMEIMAGEE1
Trajectory=Straight
ApplyRangeModifiers=yes
Trajectory.DetonationDistance=6.7
Trajectory.TargetSnapDistance=0
Trajectory.Straight.PassThrough=yes
PeacefulVanish=no
ProximityImpact=3
ProximityWarhead=SOMEWARHEADE1
ProximityDamage=40
ProximityRadius=0.4
ProximityDirect=yes
PassThroughBuilding=no
DamageEdgeAttenuation=0.75
Trajectory.Speed=300.0

; F.地锤
; 抛体在经过1帧后，每隔5帧在地面位置引爆一个额外弹头 SOMEWARHEADF1 ，
; 沿地形飞行固定距离后才会引爆，且水平方向上的速度恒定不变
[SOMEPROJECTILEF1]
AA=no
AG=yes
Inaccurate=yes
FlakScatter=yes
BallisticScatter.Min=0
BallisticScatter.Max=1
SubjectToCliffs=no
SubjectToElevation=no
SubjectToWalls=no
Image=SOMEIMAGEF1
Trajectory=Straight
ApplyRangeModifiers=yes
Trajectory.DetonationDistance=12.5
Trajectory.TargetSnapDistance=0
Trajectory.Straight.PassThrough=yes
PassDetonate=yes
PassDetonateWarhead=SOMEWARHEADF1
PassDetonateDamage=60
PassDetonateDelay=5
PassDetonateInitialDelay=1
PassDetonateLocal=yes
Trajectory.Straight.ConfineAtHeight=32
Trajectory.Speed=60.0

; G.炮射导弹
; 抛射体会像炮弹一样被发射，且还会追踪目标，当原目标消失后，会在其位置的半径内搜索一个新目标
[SOMEPROJECTILEG1]
AA=yes
AG=yes
SubjectToCliffs=no
SubjectToElevation=no
SubjectToWalls=no
Image=SOMEIMAGEG1
Trajectory=Missile
Trajectory.Missile.LaunchSpeed=50
Trajectory.Missile.Acceleration=50
Trajectory.Missile.TurningSpeed=30
RetargetRadius=2.5
Trajectory.Speed=150.0
Gravity=0

; H.扇形冲击波
; 组合体，这个抛体的逻辑和霰弹枪一样，作为初始跳板
[SOMEPROJECTILEH1]
AA=no
AG=yes
SubjectToCliffs=no
SubjectToElevation=no
SubjectToWalls=no
Image=SOMEIMAGEH1
Trajectory=Missile
Trajectory.Missile.LaunchSpeed=0
Trajectory.Missile.Acceleration=0
Trajectory.Missile.TurningSpeed=0
Trajectory.Missile.LockDirection=yes
DisperseWeapons=SOMEWEAPONH2
DisperseBursts=1
DisperseCounts=1
DisperseCycle=1
Trajectory.Speed=0

; 抛射体会等待一段时间后才会同时发射8组 SOMEWEAPONH3
[SOMEPROJECTILEH2]
AA=no
AG=yes
SubjectToCliffs=no
SubjectToElevation=no
SubjectToWalls=no
Image=SOMEIMAGEH2
Trajectory=Missile
Trajectory.Missile.LaunchSpeed=0
Trajectory.Missile.Acceleration=0
Trajectory.Missile.TurningSpeed=0
Trajectory.Missile.LockDirection=yes
DisperseWeapons=SOMEWEAPONH3
DisperseBursts=8
DisperseCounts=1
DisperseInitialDelay=100
DisperseCycle=1
Trajectory.Speed=0

; 这个抛体的逻辑和地锤一样，当偏移值足够大时，能够避免因为目标距离太近导致向量方向计算出现问题
[SOMEPROJECTILEH3]
AA=no
AG=yes
SubjectToCliffs=no
SubjectToElevation=no
SubjectToWalls=no
Image=SOMEIMAGEH3
Trajectory=Straight
ApplyRangeModifiers=yes
Trajectory.DetonationDistance=9.2
Trajectory.TargetSnapDistance=0
Trajectory.Straight.PassThrough=yes
PassDetonate=yes
PassDetonateWarhead=SOMEWARHEADH3
PassDetonateDamage=60
PassDetonateDelay=6
PassDetonateInitialDelay=15
PassDetonateLocal=yes
Trajectory.OffsetCoord=100000,0,0
Trajectory.MirrorCoord=no
Trajectory.RotateCoord=70
DamageEdgeAttenuation=2.5
Trajectory.Straight.ConfineAtHeight=500
Trajectory.Speed=40.0

; I.弹道导弹
; 简易的模拟钱学森弹道的导弹
[SOMEPROJECTILEI1]
AA=no
AG=yes
SubjectToCliffs=no
SubjectToElevation=no
SubjectToWalls=no
Image=SOMEIMAGEI1
Trajectory=Missile
Trajectory.Missile.UniqueCurve=yes

; J.激光扫射
; 简易的交叉型扫射，每2帧引爆一次额外弹头，额外弹头使用抛体弹头，伤害使用抛体伤害，
; 由于抛体设定了额外引爆，所以默认会在最后消失，而不会引爆自身再造成一次伤害
[SOMEPROJECTILEJ1]
AA=no
AG=yes
SubjectToCliffs=yes
SubjectToElevation=yes
SubjectToWalls=no
SubjectToGround=yes
Image=SOMEIMAGEJ1
Trajectory=Engrave
PassDetonate=yes
PassDetonateDelay=2
Trajectory.Engrave.SourceCoord=0,300
Trajectory.Engrave.TargetCoord=0,-300
Trajectory.Speed=40.0

; K.滚珠
; 使用固定的水平速度和角度，抛体按照设定的方向以相对稳定的轨迹发射，不会提前引爆也不会吸附到目标位置，
; 每次弹跳会引爆自身使用的弹头，在弹跳3次之后，当抛体再次遇到障碍就会引爆
[SOMEPROJECTILEK1]
AA=no
AG=yes
SubjectToCliffs=yes
SubjectToElevation=yes
SubjectToWalls=no
Image=SOMEIMAGEK1
Gravity=4.0
Trajectory=Parabola
Trajectory.Speed=50.0
Trajectory.DetonationDistance=0
Trajectory.TargetSnapDistance=0
Trajectory.Parabola.OpenFireMode=SpeedAndAngle
Trajectory.Parabola.LaunchAngle=10
Trajectory.Parabola.BounceTimes=3
Trajectory.Parabola.BounceDetonate=yes
Trajectory.OffsetCoord=0,80,0
Trajectory.RotateCoord=30

; L.双联喷火器
; 这个抛体的逻辑和喷火器类似，可穿过车辆并造成伤害，并通过目标偏移和镜像坐标来达到并联发射的效果
[SOMEPROJECTILEL1]
AA=no
AG=yes
Inaccurate=yes
FlakScatter=yes
BallisticScatter.Min=0
BallisticScatter.Max=0.6
SubjectToCliffs=yes
SubjectToElevation=no
SubjectToWalls=yes
SubjectToBuildings=yes
Image=SOMEIMAGEL1
Trajectory=Straight
Trajectory.DetonationDistance=5.2
Trajectory.TargetSnapDistance=0
Trajectory.Straight.PassThrough=yes
Trajectory.OffsetCoord=0,115,0
ProximityImpact=-1
ProximityWarhead=SOMEWARHEADL1
ProximityDamage=40
ProximityRadius=0.8
ProximityDirect=yes
ProximityAllies=yes
PassThroughBuilding=no
Trajectory.Straight.ConfineAtHeight=105
Trajectory.Speed=60.0

; M.垂发导弹
; 抛射体先垂直向上移动，在这个过程中，导弹就会先面朝目标方向
[SOMEPROJECTILEM1]
AA=yes
AG=yes
SubjectToCliffs=no
SubjectToElevation=no
SubjectToWalls=no
Image=SOMEIMAGEM1
Trajectory=Missile
Trajectory.BulletROT=6
Trajectory.BulletFacing=Target
Trajectory.Missile.PreAimCoord=0,0,240
Trajectory.Missile.ReduceCoord=no
Trajectory.Missile.LaunchSpeed=20
Trajectory.Missile.Acceleration=12
RetargetRadius=5
Trajectory.Speed=200.0

; N.定向激光扫射
; 这个抛体的逻辑和激光扫射类似，以纵向直线扫射代替横向交叉扫射
[SOMEPROJECTILEN1]
AA=no
AG=yes
SubjectToCliffs=yes
SubjectToElevation=no
SubjectToWalls=no
Image=SOMEIMAGEN1
Trajectory=Engrave
PassDetonate=yes
PassDetonateDelay=2
LifeDuration=75
Trajectory.Speed=40.0

; O.开花弹
; 当抛射体最后要引爆的时候，同时发射12组 SOMEWEAPONO2
[SOMEPROJECTILEO1]
AA=no
AG=yes
SubjectToCliffs=no
SubjectToElevation=yes
SubjectToWalls=no
Image=SOMEIMAGEO1
Trajectory=Parabola
Trajectory.Parabola.OpenFireMode=Speed
PeacefulVanish=no
DisperseSuicide=yes
DisperseWeapons=SOMEWEAPONO2
DisperseBursts=12
DisperseCounts=1
DisperseCycle=1
DisperseEffectiveRange=-1
Trajectory.Speed=200.0
Gravity=12.0

; 这个抛体的逻辑结合了扇形冲击波和滚珠，弹性系数越高，能让抛体在弹跳后飞得越远
[SOMEPROJECTILEO2]
AA=no
AG=yes
SubjectToCliffs=no
SubjectToElevation=no
SubjectToWalls=no
Image=SOMEIMAGEO2
Trajectory=Parabola
Trajectory.DetonationDistance=0
Trajectory.TargetSnapDistance=0
Trajectory.Parabola.OpenFireMode=SpeedAndAngle
Trajectory.Parabola.LaunchAngle=60
Trajectory.Parabola.BounceTimes=3
Trajectory.Parabola.BounceOnTarget=all
Trajectory.Parabola.BounceDetonate=yes
Trajectory.Parabola.BounceAttenuation=0.9
Trajectory.Parabola.BounceCoefficient=0.9
Trajectory.OffsetCoord=100000,0,0
Trajectory.RotateCoord=330
Trajectory.MirrorCoord=no
Trajectory.Speed=40.0
Gravity=8.0

; P.集束火炮
; 这个抛体的逻辑和霰弹枪类似，将发射武器的时机推迟到了抛物线的最高点上，
; 并通过记录原目标格子的位置，可以避免出现较大的转折角度和过于精准的攻击
[SOMEPROJECTILEP1]
AA=no
AG=yes
SubjectToCliffs=no
SubjectToElevation=yes
SubjectToWalls=no
Image=SOMEIMAGEP1
Trajectory=Parabola
Trajectory.DetonationDistance=-1
Trajectory.TargetSnapDistance=0
Trajectory.Parabola.OpenFireMode=Angle
Trajectory.Parabola.LaunchAngle=65.0
Trajectory.Parabola.DetonationAngle=0
DisperseWeapons=SOMEWEAPONP2
DisperseBursts=3
DisperseCounts=1
DisperseCycle=1
DisperseEffectiveRange=-1
DisperseRetarget=yes

; 水平发射的抛物线抛体
[SOMEPROJECTILEP2]
AA=no
AG=yes
SubjectToCliffs=no
SubjectToElevation=no
SubjectToWalls=no
Image=SOMEIMAGEP2
Trajectory=Parabola
Trajectory.DetonationDistance=0.2
Trajectory.TargetSnapDistance=0.2
Trajectory.Parabola.OpenFireMode=Angle
Trajectory.Parabola.LaunchAngle=0.0

; Q.自爆球
; 抛体发射后会持续追踪目标，只有在固定100帧后才会引爆
[SOMEPROJECTILEQ1]
AA=no
AG=yes
SubjectToCliffs=no
SubjectToElevation=no
SubjectToWalls=no
Image=SOMEIMAGEQ1
Trajectory=Tracing
LifeDuration=100
Synchronize=yes
Trajectory.Tracing.ChasableDistance=-16
Trajectory.Speed=40.0

; R.轨道打击
; 抛体从目标上空自由落体，并通过 SOMEWEAPONR2 实现伤害落点提示
[SOMEPROJECTILER1]
AA=no
AG=yes
SubjectToCliffs=no
SubjectToElevation=no
SubjectToWalls=no
Image=SOMEIMAGER1
Trajectory=Bombard
Trajectory.Bombard.Height=12000.0
Trajectory.Bombard.NoLaunch=yes
PeacefulVanish=no
DisperseSuicide=no
DisperseWeapons=SOMEWEAPONR2
DisperseBursts=1
DisperseCounts=1
DisperseCycle=1
Gravity=15.0

; S.浮游炮
; 抛体会绕着发射者飞行，并朝向发射者的目标，每隔一段时间向目标发射 SOMEWEAPONS2 ，
; 抛体同时能存在3个，抛体的朝向如果和目标的方向差距过大，或目标距离太远，则无法发射武器，
; 当发射者完全失去目标30帧后，这组抛体会消失
[SOMEPROJECTILES1]
AA=no
AG=yes
SubjectToCliffs=no
SubjectToElevation=no
SubjectToWalls=no
Image=SOMEIMAGES1
Trajectory=Tracing
Trajectory.Tracing.TraceMode=RotateCW
Trajectory.Tracing.StableRotation=yes
Trajectory.Tracing.TrackTarget=no
Trajectory.Tracing.AttachCoord=520,0,-200
LifeDuration=-1
NoTargetLifeTime=30
CreateCapacity=3
Trajectory.BulletROT=3
Trajectory.BulletFacing=Target
Trajectory.BulletFacingOnPlane=yes
PeacefulVanish=yes
Synchronize=yes
DisperseCoord=100,0,0
DisperseFromFirer=no
DisperseWeapons=SOMEWEAPONS2
DisperseBursts=2
DisperseCounts=-1
DisperseDelays=40
DisperseCycle=1
DisperseRetarget=yes
DisperseTendency=yes
DisperseFaceCheck=yes
DisperseForceFire=no
Trajectory.Speed=30.0

[SOMEPROJECTILES2]
AA=yes
AG=yes
SubjectToCliffs=no
SubjectToElevation=no
SubjectToWalls=no
Image=SOMEIMAGES2
Trajectory=Missile
Trajectory.Missile.PreAimCoord=0,0,-50
Trajectory.Missile.ReduceCoord=no
Trajectory.Missile.LaunchSpeed=50
Trajectory.Missile.Acceleration=5
Trajectory.Missile.TurningSpeed=12
Trajectory.Missile.RetargetRadius=2.5
Trajectory.Missile.CruiseEnable=yes
Trajectory.Missile.CruiseUnableRange=3.0
Trajectory.Missile.CruiseAltitude=450
Trajectory.Missile.CruiseAlongLevel=yes
Trajectory.Speed=90.0

; T.无人机群
; 这个抛体的逻辑和浮游炮类似，环绕的目标是发射者的目标，当目标距离超出射程时将不再能够追到目标
[SOMEPROJECTILET1]
AA=yes
AG=yes
SubjectToCliffs=no
SubjectToElevation=no
SubjectToWalls=no
Image=SOMEIMAGET1
Trajectory=Tracing
Trajectory.Tracing.TraceMode=RotateCCW
Trajectory.Tracing.StableRotation=yes
Trajectory.Tracing.AttachCoord=640,0,500
Trajectory.Tracing.ChasableDistance=10
Synchronize=yes
LifeDuration=-1
NoTargetLifeTime=0
CreateCapacity=5
Trajectory.BulletFacing=Target
PeacefulVanish=yes
DisperseCoord=100,0,0
DisperseFromFirer=no
DisperseWeapons=SOMEWEAPONT2
DisperseBursts=1
DisperseCounts=-1
DisperseDelays=1
DisperseInitialDelay=50
DisperseCycle=-1
DisperseForceFire=no
Trajectory.Speed=45.0

; U.多重激光扫射
; 这个抛体的逻辑和霰弹枪类似，记录发射位置以供后续的三道扫射激光使用
[SOMEPROJECTILEU1]
AA=no
AG=yes
SubjectToCliffs=no
SubjectToElevation=yes
SubjectToWalls=no
SubjectToGround=yes
Image=SOMEIMAGEU1
Trajectory=Missile
Trajectory.Missile.LaunchSpeed=0
Trajectory.Missile.Acceleration=0
Trajectory.Missile.TurningSpeed=0
DisperseSuicide=yes
DisperseWeapons=SOMEWEAPONU2,SOMEWEAPONU3,SOMEWEAPONU4
DisperseBursts=1
DisperseCounts=1
DisperseCycle=1
Trajectory.Speed=0

; 这个抛体的逻辑和激光扫射类似，使用跳板的发射位置，会持续更新目标方向和位置，且不允许发射者炮塔的朝向偏离过多
[SOMEPROJECTILEU2]
AA=no
AG=yes
SubjectToCliffs=no
SubjectToElevation=yes
SubjectToWalls=no
Image=SOMEIMAGEU2
Trajectory=Engrave
PassDetonate=yes
PassDetonateDelay=2
Trajectory.Engrave.SourceCoord=0,600
Trajectory.Engrave.TargetCoord=0,-600
UseDisperseCoord=yes
Trajectory.AllowFirerTurning=no
Trajectory.Engrave.AttachToTarget=yes
Trajectory.Engrave.UpdateDirection=yes
Trajectory.Speed=40.0

[SOMEPROJECTILEU3]:[SOMEPROJECTILEU2]
Trajectory.Engrave.SourceCoord=300,520
Trajectory.Engrave.TargetCoord=-300,-520

[SOMEPROJECTILEU4]:[SOMEPROJECTILEU2]
Trajectory.Engrave.SourceCoord=-300,520
Trajectory.Engrave.TargetCoord=300,-520

; V.收束激光
; 这个抛体的逻辑和霰弹枪类似，记录发射位置以供后续的所有武器使用
[SOMEPROJECTILEV1]
AA=no
AG=yes
SubjectToCliffs=no
SubjectToElevation=yes
SubjectToWalls=no
SubjectToGround=yes
Image=SOMEIMAGEV1
Trajectory=Missile
Trajectory.Missile.LaunchSpeed=0
Trajectory.Missile.Acceleration=0
Trajectory.Missile.TurningSpeed=0
DisperseSuicide=yes
DisperseWeapons=SOMEWEAPONV2,SOMEWEAPONV3,SOMEWEAPONV4
DisperseBursts=1
DisperseCounts=1
DisperseCycle=1
Trajectory.Speed=0

; 这个抛体的逻辑和多重激光扫射一样
[SOMEPROJECTILEV2]
AA=no
AG=yes
SubjectToCliffs=no
SubjectToElevation=yes
SubjectToWalls=no
Image=SOMEIMAGEV2
Trajectory=Engrave
Trajectory.Engrave.SourceCoord=0,400
Trajectory.Engrave.TargetCoord=0,0
UseDisperseCoord=yes
Trajectory.AllowFirerTurning=no
Trajectory.Engrave.AttachToTarget=yes
Trajectory.Engrave.UpdateDirection=yes
Trajectory.Speed=10.0

[SOMEPROJECTILEV3]:[SOMEPROJECTILEV2]
Trajectory.Engrave.SourceCoord=0,-400

; 这个抛体的逻辑和扇形冲击波类似，当发射者失去目标或更换目标时，进程会被打断，在跟随目标40帧后，武器会分组按顺序发射，
; SOMEWEAPONV5 可以是更粗的激光，并实现持续追踪的效果，SOMEWEAPONV6 可以是最终发射的伤害类武器
[SOMEPROJECTILEV4]
AA=no
AG=yes
SubjectToCliffs=no
SubjectToElevation=no
SubjectToWalls=no
SubjectToGround=no
Image=SOMEIMAGEV4
Trajectory=Tracing
LifeDuration=80
NoTargetLifeTime=0
UseDisperseCoord=yes
PeacefulVanish=yes
Synchronize=yes
Trajectory.AllowFirerTurning=no
DisperseWeapons=SOMEWEAPONV5,SOMEWEAPONV6
DisperseBursts=1
DisperseCounts=10,1
DisperseDelays=1
DisperseInitialDelay=40
DisperseCycle=1
DisperseSeparate=yes
DisperseSuicide=yes
Trajectory.Tracing.CreateAtTarget=yes
Trajectory.Tracing.ChasableDistance=15
Trajectory.Speed=10000.0

; W.球状闪电
; 这个抛体的逻辑和自爆球相同，增加了向周围目标发射武器的效果
[SOMEPROJECTILEW1]
AA=no
AG=yes
SubjectToCliffs=no
SubjectToElevation=no
SubjectToWalls=no
Image=SOMEIMAGEW1
Trajectory=Tracing
LifeDuration=210
NoTargetLifeTime=30
Synchronize=yes
Trajectory.Tracing.CreateCoord=150,0,0
PassDetonate=yes
PassDetonateWarhead=SOMEWARHEADW2
PassDetonateDamage=40
PassDetonateDelay=5
PassDetonateInitialDelay=1
DisperseWeapons=SOMEWEAPONW2
DisperseBursts=3
DisperseCounts=-1
DisperseDelays=30
DisperseInitialDelay=40
DisperseCycle=1
DisperseRetarget=yes
DisperseLocation=yes
DisperseFromFirer=no
DisperseForceFire=no
Trajectory.Speed=20.0
